#!/usr/bin/env bash

# Prune-OPD reproduction for 2605.07804v3. All non-method parameters inherit opd_4b.sh.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export METHOD=${METHOD:-prune_opd}
export G_OPD_ENABLE=False
export PRUNE_OPD_ENABLE=${PRUNE_OPD_ENABLE:-True}
export PRUNE_OPD_OVERLAP_THRESHOLD=${PRUNE_OPD_OVERLAP_THRESHOLD:-0.7}
export PRUNE_OPD_WDROP=${PRUNE_OPD_WDROP:-0.01}
export PRUNE_OPD_WBASE=${PRUNE_OPD_WBASE:-0.5}
export PRUNE_OPD_DYNAMIC_LENGTH_ENABLE=${PRUNE_OPD_DYNAMIC_LENGTH_ENABLE:-True}
export PRUNE_OPD_DYNAMIC_INITIAL_LENGTH=${PRUNE_OPD_DYNAMIC_INITIAL_LENGTH:-2048}
export PRUNE_OPD_DYNAMIC_MIN_LENGTH=${PRUNE_OPD_DYNAMIC_MIN_LENGTH:-1024}
export PRUNE_OPD_DYNAMIC_MAX_LENGTH=${PRUNE_OPD_DYNAMIC_MAX_LENGTH:-12288}
export PRUNE_OPD_DYNAMIC_STEP=${PRUNE_OPD_DYNAMIC_STEP:-100}
export PRUNE_OPD_DYNAMIC_MARGIN=${PRUNE_OPD_DYNAMIC_MARGIN:-100}
export PRUNE_OPD_DYNAMIC_HIT_RATIO=${PRUNE_OPD_DYNAMIC_HIT_RATIO:-0.1}
export PRUNE_OPD_DYNAMIC_SHRINK_PATIENCE=${PRUNE_OPD_DYNAMIC_SHRINK_PATIENCE:-3}
export PRUNE_OPD_DYNAMIC_EPSILON=${PRUNE_OPD_DYNAMIC_EPSILON:-1e-8}

# Match the official DeepSeek/JustRL launcher: do not pass enable_thinking.
export ENABLE_THINKING=

# Validation sampling configuration.
export MAX_VAL_RESP_LENGTH=${MAX_VAL_RESP_LENGTH:-31744}
export VAL_TEMPERATURE=${VAL_TEMPERATURE:-0.7}
export VAL_TOP_P=${VAL_TOP_P:-0.95}
export VAL_N=${VAL_N:-16}

exec bash "$SCRIPT_DIR/opd_4b.sh" "$@"
